#!/bin/bash

lines="-b -l 20"
TOTAL_MEM=$(free -m | grep Mem: | awk '{print $2}')
MEM_USED=$(free -m | grep Mem: | awk '{print $3}')

selected="$(ps -a -u $USER | \
            dmenu -p " $MEM_USED""MB"/$TOTAL_MEM"MB" \
            $lines | \
            awk '{print $1" "$4}')"; 

if [[ ! -z $selected ]]; then

    answer="$(echo -e "Yes\nNo" | \
            dmenu -p " $selected will be killed, are you sure?" \
            $lines $colors $font )"

    if [[ $answer == "Yes" ]]; then
        selpid="$(awk '{print $1}' <<< $selected)"; 
        kill -9 $selpid
    fi
fi

exit 0
