#!/bin/sh
browser=${BROWSER:-firefox}

pgrep -x dmenu && exit

choice=$(echo "google\nyoutube" | dmenu -i -b -p "Search Google:") || exit 1

if [ "$choice" = "google"  ]; then
    $browser "https://google.com"
elif [ "$choice" = "youtube"  ]; then
    $browser "https://youtube.com"
else
    if echo "$choice" | grep "^(http:\/\/|https:\/\/)?[a-zA-Z0-9]+\.[a-zA-Z]+(/)?.*$"; then
        $browser "$choice"
    else
        $browser "https://google.com/search?q=$choice"
    fi
fi
