#!/bin/sh
#
# Launches files based on their mimetypes
# Usage: launch [FILE...]
# Dependencies: file

case $(file --mime-type "$@" -bL) in
    video/* | audio/* | image/gif)
      devour mpv "$@"
      ;;
   application/pdf | application/postscript)
      devour zathura "$@"
      ;;
   *) exit 1 ;;
esac
